/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggTDigest : T-Digest settings for approximate statistical aggregations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggTDigest {
    /// Accuracy/memory trade-off. Default is 200.
    #[serde(rename = "compression", skip_serializing_if = "Option::is_none")]
    pub compression: Option<f64>,
}

impl AggTDigest {
    /// T-Digest settings for approximate statistical aggregations
    pub fn new() -> AggTDigest {
        AggTDigest {
            compression: None,
        }
    }
}

