/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggBucket : Single bucket in an aggregation result
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggBucket {
    #[serde(rename = "key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub key: Option<Option<serde_json::Value>>,
    /// Number of documents in the bucket
    #[serde(rename = "doc_count")]
    pub doc_count: i32,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::FacetBucketStatus>,
}

impl AggBucket {
    /// Single bucket in an aggregation result
    pub fn new(doc_count: i32) -> AggBucket {
        AggBucket {
            key: None,
            doc_count,
            status: None,
        }
    }
}

