/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggMetric : Metric aggregation over a numeric field
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggMetric {
    /// Numeric field to aggregate
    #[serde(rename = "field")]
    pub field: String,
}

impl AggMetric {
    /// Metric aggregation over a numeric field
    pub fn new(field: String) -> AggMetric {
        AggMetric {
            field,
        }
    }
}

