/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggPercentiles : Object to use percentile values in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILES(),-PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggPercentiles {
    /// Numeric field to calculate percentiles for
    #[serde(rename = "field")]
    pub field: String,
    /// Percentile points to compute (0-100). Defaults to 1, 5, 25, 50, 75, 95, and 99 when omitted. 
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f64>>,
    /// Return an object keyed by percentile when true, or an array when false. Default is false. 
    #[serde(rename = "keyed", skip_serializing_if = "Option::is_none")]
    pub keyed: Option<bool>,
    #[serde(rename = "tdigest", skip_serializing_if = "Option::is_none")]
    pub tdigest: Option<Box<models::AggTDigest>>,
}

impl AggPercentiles {
    /// Object to use percentile values in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILES(),-PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
    pub fn new(field: String) -> AggPercentiles {
        AggPercentiles {
            field,
            values: None,
            keyed: None,
            tdigest: None,
        }
    }
}

