/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggRange : Group documents into custom numeric or date ranges. Use with the `range` or `date_range` aggregation type. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggRange {
    /// Attribute to group by
    #[serde(rename = "field")]
    pub field: String,
    /// Ordered list of ranges
    #[serde(rename = "ranges")]
    pub ranges: Vec<models::Range>,
    /// Return buckets as an object keyed by range label when true, or as an array when false. Default is false. 
    #[serde(rename = "keyed", skip_serializing_if = "Option::is_none")]
    pub keyed: Option<bool>,
}

impl AggRange {
    /// Group documents into custom numeric or date ranges. Use with the `range` or `date_range` aggregation type. 
    pub fn new(field: String, ranges: Vec<models::Range>) -> AggRange {
        AggRange {
            field,
            ranges,
            keyed: None,
        }
    }
}

