/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggPercentileRanks : Object to use percentile ranks in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggPercentileRanks {
    /// Numeric field to calculate percentile ranks for
    #[serde(rename = "field")]
    pub field: String,
    /// Input values to rank
    #[serde(rename = "values")]
    pub values: Vec<f64>,
    /// Return an object keyed by input value when true, or an array when false. Default is false. 
    #[serde(rename = "keyed", skip_serializing_if = "Option::is_none")]
    pub keyed: Option<bool>,
    #[serde(rename = "tdigest", skip_serializing_if = "Option::is_none")]
    pub tdigest: Option<Box<models::AggTDigest>>,
}

impl AggPercentileRanks {
    /// Object to use percentile ranks in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
    pub fn new(field: String, values: Vec<f64>) -> AggPercentileRanks {
        AggPercentileRanks {
            field,
            values,
            keyed: None,
            tdigest: None,
        }
    }
}

