/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggMedianAbsoluteDeviation : Object to use median absolute deviation in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILES(),-PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggMedianAbsoluteDeviation {
    /// Numeric field to calculate MAD for
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "tdigest", skip_serializing_if = "Option::is_none")]
    pub tdigest: Option<Box<models::AggTDigest>>,
}

impl AggMedianAbsoluteDeviation {
    /// Object to use median absolute deviation in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILES(),-PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
    pub fn new(field: String) -> AggMedianAbsoluteDeviation {
        AggMedianAbsoluteDeviation {
            field,
            tdigest: None,
        }
    }
}

