/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Chat : Conversational search request handled by Manticore Buddy via `CALL CHAT`. When this object is set, the `/search` endpoint answers through an LLM using KNN-retrieved rows as context instead of returning regular search hits. Required fields are `query`, `table`, and `model_name`. Chat model management (`CREATE CHAT MODEL`, etc.) remains SQL-only. For more information see [Conversational search](https://manual.manticoresearch.com/Searching/Conversational_search#HTTP-JSON-syntax) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chat {
    /// User question to send to the chat model
    #[serde(rename = "query")]
    pub query: String,
    /// Vectorized table to retrieve context from
    #[serde(rename = "table")]
    pub table: String,
    /// Name of the chat model
    #[serde(rename = "model_name")]
    pub model_name: String,
    /// Existing conversation id to continue the dialog, or an empty string to start a new conversation. If omitted, a new id is generated. 
    #[serde(rename = "conversation_uuid", skip_serializing_if = "Option::is_none")]
    pub conversation_uuid: Option<String>,
    /// A specific vector field to search by. If omitted, Buddy uses the first `FLOAT_VECTOR` field from `SHOW CREATE TABLE`. 
    #[serde(rename = "vector_field", skip_serializing_if = "Option::is_none")]
    pub vector_field: Option<String>,
    /// Legacy alias for `vector_field`. A request must not include both `vector_field` and `fields`. 
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<String>,
}

impl Chat {
    /// Conversational search request handled by Manticore Buddy via `CALL CHAT`. When this object is set, the `/search` endpoint answers through an LLM using KNN-retrieved rows as context instead of returning regular search hits. Required fields are `query`, `table`, and `model_name`. Chat model management (`CREATE CHAT MODEL`, etc.) remains SQL-only. For more information see [Conversational search](https://manual.manticoresearch.com/Searching/Conversational_search#HTTP-JSON-syntax) 
    pub fn new(query: String, table: String, model_name: String) -> Chat {
        Chat {
            query,
            table,
            model_name,
            conversation_uuid: None,
            vector_field: None,
            fields: None,
        }
    }
}

