/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FacetFilterMode : Controls how facets inherit attribute filters from the main query. [Faceted search](https://manual.manticoresearch.com/Searching/Faceted_search#HTTP-JSON) 
/// Controls how facets inherit attribute filters from the main query. [Faceted search](https://manual.manticoresearch.com/Searching/Faceted_search#HTTP-JSON) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FacetFilterMode {
    #[serde(rename = "strict")]
    Strict,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "max")]
    Max,

}

impl std::fmt::Display for FacetFilterMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Strict => write!(f, "strict"),
            Self::Auto => write!(f, "auto"),
            Self::Max => write!(f, "max"),
        }
    }
}

impl Default for FacetFilterMode {
    fn default() -> FacetFilterMode {
        Self::Strict
    }
}

