/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Hybrid : Perform hybrid search on tables with auto-embeddings. Runs full-text and vector search and fuses results with RRF.  For more information see [Hybrid search](https://manual.manticoresearch.com/Searching/Hybrid_search#Simplified-JSON-syntax:-hybrid) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Hybrid {
    /// Search query string
    #[serde(rename = "query")]
    pub query: String,
    /// Vector field name. 
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
}

impl Hybrid {
    /// Perform hybrid search on tables with auto-embeddings. Runs full-text and vector search and fuses results with RRF.  For more information see [Hybrid search](https://manual.manticoresearch.com/Searching/Hybrid_search#Simplified-JSON-syntax:-hybrid) 
    pub fn new(query: String) -> Hybrid {
        Hybrid {
            query,
            field: None,
        }
    }
}

