/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Range : An aggregation range. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Range {
    #[serde(rename = "from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from: Option<Option<serde_json::Value>>,
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<serde_json::Value>>,
}

impl Range {
    /// An aggregation range. 
    pub fn new() -> Range {
        Range {
            from: None,
            to: None,
        }
    }
}

