/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScriptFieldScript : Inline script used to compute a search expression
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptFieldScript {
    /// Expression to compute (same syntax as SQL expressions)
    #[serde(rename = "inline")]
    pub inline: String,
}

impl ScriptFieldScript {
    /// Inline script used to compute a search expression
    pub fn new(inline: String) -> ScriptFieldScript {
        ScriptFieldScript {
            inline,
        }
    }
}

