/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScriptField : Named expression computed at search time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptField {
    #[serde(rename = "script")]
    pub script: Box<models::ScriptFieldScript>,
}

impl ScriptField {
    /// Named expression computed at search time
    pub fn new(script: models::ScriptFieldScript) -> ScriptField {
        ScriptField {
            script: Box::new(script),
        }
    }
}

